import os

SRC = os.path.join(os.path.dirname(__file__), "src")

FILES = {
    "config.py": [
        '"""Application configuration."""',
        "",
        "import os",
        "from dataclasses import dataclass",
        "from pathlib import Path",
        "",
        "",
        "@dataclass(frozen=True)",
        "class Settings:",
        '    HOST: str = "0.0.0.0"',
        "    PORT: int = 8000",
        '    OLLAMA_URL: str = "http://localhost:11434"',
        '    MODEL_NAME: str = "qwen2.5:1.5b"',
        '    DATABASE_PATH: Path = Path("./motu.db")',
        '    LOG_LEVEL: str = "INFO"',
        "",
        "    @classmethod",
        '    def from_env(cls) -> "Settings":',
        "        return cls(",
        "            HOST=os.getenv('MOTU_HOST', cls.HOST),",
        "            PORT=int(os.getenv('MOTU_PORT', cls.PORT)),",
        "            OLLAMA_URL=os.getenv('MOTU_OLLAMA_URL', cls.OLLAMA_URL),",
        "            MODEL_NAME=os.getenv('MOTU_MODEL_NAME', cls.MODEL_NAME),",
        "            DATABASE_PATH=Path(os.getenv('MOTU_DATABASE_PATH', str(cls.DATABASE_PATH))),",
        "            LOG_LEVEL=os.getenv('MOTU_LOG_LEVEL', cls.LOG_LEVEL),",
        "        )",
        "",
        "",
        "settings = Settings.from_env()",
    ],

    "idgen.py": [
        '"""Time-ordered UUIDv7 generator (RFC 9562)."""',
        "",
        "import time",
        "import uuid",
        "",
        "",
        "def uuid7() -> str:",
        '    timestamp_ms = int(time.time() * 1000)',
        '    timestamp_bytes = timestamp_ms.to_bytes(6, "big")',
        '    rand_bytes = uuid.uuid4().bytes',
        '    v7 = bytearray(16)',
        '    v7[0:6] = timestamp_bytes',
        '    v7[6] = (rand_bytes[6] & 0x0F) | 0x70',
        '    v7[7] = (rand_bytes[7] & 0x3F) | 0x80',
        '    v7[8:16] = rand_bytes[8:16]',
        '    return str(uuid.UUID(bytes=bytes(v7)))',
        "",
        "",
        "def uuid7_to_datetime(uuid_str: str) -> float:",
        '    u = uuid.UUID(uuid_str)',
        '    timestamp_ms = int.from_bytes(u.bytes[0:6], "big")',
        '    return timestamp_ms / 1000.0',
    ],

    "db.py": [
        '"""SQLite database setup with WAL mode."""',
        "",
        "from sqlalchemy import create_engine, event",
        "from sqlalchemy.orm import sessionmaker, declarative_base",
        "",
        "from config import settings",
        "",
        'DB_URL = f"sqlite:///{settings.DATABASE_PATH.resolve()}"',
        "",
        "engine = create_engine(",
        '    DB_URL,',
        '    connect_args={"check_same_thread": False},',
        "    pool_pre_ping=True,",
        "    echo=False,",
        ")",
        "",
        "",
        "@event.listens_for(engine, 'connect')",
        "def _set_sqlite_pragma(dbapi_conn, connection_record):",
        '    cursor = dbapi_conn.cursor()',
        '    cursor.execute("PRAGMA journal_mode=WAL")',
        '    cursor.execute("PRAGMA foreign_keys=ON")',
        '    cursor.execute("PRAGMA synchronous=NORMAL")',
        "    cursor.close()",
        "",
        "",
        "SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)",
        "Base = declarative_base()",
        "",
        "",
        "def init_db() -> None:",
        "    Base.metadata.create_all(bind=engine)",
    ],

    "orm.py": [
        '"""SQLAlchemy ORM models."""',
        "",
        "from datetime import datetime, timezone",
        "from typing import List",
        "",
        "from sqlalchemy import String, Text, Index, ForeignKey",
        "from sqlalchemy.orm import Mapped, mapped_column, relationship",
        "",
        "from db import Base",
        "from idgen import uuid7",
        "",
        "",
        "def utc_now() -> datetime:",
        "    return datetime.now(timezone.utc)",
        "",
        "",
        "class Session(Base):",
        '    __tablename__ = "sessions"',
        "",
        '    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=uuid7)',
        '    title: Mapped[str] = mapped_column(String(255), default="New Chat")',
        '    model: Mapped[str] = mapped_column(String(100), default="qwen2.5:1.5b")',
        "    created_at: Mapped[datetime] = mapped_column(default=utc_now)",
        "    updated_at: Mapped[datetime] = mapped_column(default=utc_now, onupdate=utc_now)",
        "",
        '    messages: Mapped[List["Message"]] = relationship(',
        '        back_populates="session",',
        '        cascade="all, delete-orphan",',
        '        order_by="Message.created_at",',
        "    )",
        "",
        '    __table_args__ = (Index("idx_sessions_updated", "updated_at"),)',
        "",
        "",
        "class Message(Base):",
        '    __tablename__ = "messages"',
        "",
        '    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=uuid7)',
        '    session_id: Mapped[str] = mapped_column(',
        '        String(36), ForeignKey("sessions.id", ondelete="CASCADE"), nullable=False',
        "    )",
        '    role: Mapped[str] = mapped_column(String(20), nullable=False)',
        '    content: Mapped[str] = mapped_column(Text, nullable=False)',
        "    created_at: Mapped[datetime] = mapped_column(default=utc_now)",
        "",
        '    session: Mapped["Session"] = relationship(back_populates="messages")',
        "",
        '    __table_args__ = (Index("idx_messages_session", "session_id", "created_at"),)',
    ],

    "schemas.py": [
        '"""Pydantic request/response models."""',
        "",
        "from datetime import datetime",
        "from typing import List, Optional",
        "",
        "from pydantic import BaseModel, ConfigDict",
        "",
        "",
        "class MessageResponse(BaseModel):",
        "    model_config = ConfigDict(from_attributes=True)",
        "    id: str",
        "    session_id: str",
        "    role: str",
        "    content: str",
        "    created_at: datetime",
        "",
        "",
        "class SessionCreate(BaseModel):",
        "    title: Optional[str] = None",
        "    model: Optional[str] = None",
        "",
        "",
        "class SessionResponse(BaseModel):",
        "    model_config = ConfigDict(from_attributes=True)",
        "    id: str",
        "    title: str",
        "    model: str",
        "    created_at: datetime",
        "    updated_at: datetime",
        "    message_count: int",
        "",
        "",
        "class SessionDetailResponse(BaseModel):",
        "    model_config = ConfigDict(from_attributes=True)",
        "    id: str",
        "    title: str",
        "    model: str",
        "    created_at: datetime",
        "    updated_at: datetime",
        "    messages: List[MessageResponse]",
        "",
        "",
        "class SessionListResponse(BaseModel):",
        "    sessions: List[SessionResponse]",
        "",
        "",
        "class ChatRequest(BaseModel):",
        "    session_id: Optional[str] = None",
        "    message: str",
        "",
        "",
        "class ModelInfo(BaseModel):",
        "    name: str",
        "    size: int",
        "    parameter_count: str",
        "    format: str",
        "",
        "",
        "class ModelListResponse(BaseModel):",
        "    models: List[ModelInfo]",
        "",
        "",
        "class ActiveModelResponse(BaseModel):",
        "    active_model: str",
        "",
        "",
        "class HealthResponse(BaseModel):",
        "    status: str",
        "    version: str",
        "    uptime: float",
        "    cpu_percent: float",
        "    memory_percent: float",
        "    memory_used_gb: float",
        "    ollama_connected: bool",
    ],

    "deps.py": [
        '"""FastAPI database dependency."""',
        "",
        "from typing import Generator",
        "",
        "from sqlalchemy.orm import Session",
        "",
        "from db import SessionLocal",
        "",
        "",
        "def get_db() -> Generator[Session, None, None]:",
        "    db = SessionLocal()",
        "    try:",
        "        yield db",
        "    finally:",
        "        db.close()",
    ],

    "ollama_client.py": [
        '"""Async HTTP client for local Ollama instance."""',
        "",
        "import json",
        "import logging",
        "from typing import AsyncGenerator, List, Dict, Any",
        "",
        "import httpx",
        "",
        "from config import settings",
        "",
        'logger = logging.getLogger(__name__)',
        "",
        "_client: httpx.AsyncClient | None = None",
        "",
        "",
        "def get_client() -> httpx.AsyncClient:",
        '    global _client',
        "    if _client is None:",
        "        _client = httpx.AsyncClient(",
        '            base_url=settings.OLLAMA_URL,',
        '            timeout=httpx.Timeout(120.0, connect=5.0),',
        "        )",
        "    return _client",
        "",
        "",
        "async def close_client() -> None:",
        '    global _client',
        "    if _client is not None:",
        "        await _client.aclose()",
        "        _client = None",
        "",
        "",
        "async def check_health() -> bool:",
        "    try:",
        "        client = get_client()",
        '        resp = await client.get("/api/tags", timeout=3.0)',
        "        return resp.status_code == 200",
        "    except Exception:",
        "        return False",
        "",
        "",
        "async def list_models() -> List[Dict[str, Any]]:",
        '    client = get_client()',
        '    resp = await client.get("/api/tags")',
        "    resp.raise_for_status()",
        "    data = resp.json()",
        "",
        "    models = []",
        '    for m in data.get("models", []):',
        '        name = m.get("name", "unknown")',
        "        size = m.get('size', 0)",
        '        param_count = "unknown"',
        '        if ":" in name:',
        '            tag = name.split(":")[1]',
        '            if "b" in tag.lower():',
        '                param_count = tag.lower().replace("b", "B")',
        "        models.append({",
        '            "name": name,',
        '            "size": size,',
        '            "parameter_count": param_count,',
        '            "format": m.get("details", {}).get("format", "gguf"),',
        "        })",
        "    return models",
        "",
        "",
        "async def stream_chat(",
        '    messages: List[Dict[str, str]],',
        '    model: str | None = None,',
        ") -> AsyncGenerator[str, None]:",
        '    client = get_client()',
        "    model = model or settings.MODEL_NAME",
        "",
        "    payload = {",
        '        "model": model,',
        '        "messages": messages,',
        '        "stream": True,',
        "    }",
        "",
        '    async with client.stream("POST", "/api/chat", json=payload) as resp:',
        "        resp.raise_for_status()",
        '        async for line in resp.aiter_lines():',
        "            if not line.strip():",
        "                continue",
        "            try:",
        "                data = json.loads(line)",
        "            except json.JSONDecodeError:",
        '                logger.warning("Ollama sent invalid JSON: %s", line)',
        "                continue",
        "",
        '            msg = data.get("message", {})',
        '            token = msg.get("content", "")',
        "            if token:",
        "                yield token",
        "",
        '            if data.get("done"):',
        "                break",
    ],
}

for name, lines in FILES.items():
    path = os.path.join(SRC, name)
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"Restored: {path}")

print("\nAll 7 V2 files restored. Run: py test_m1.py && py test_m2.py")