import os

SRC = os.path.join(os.path.dirname(__file__), "src")

FILES = {
    "config.py": [
        '"""Application configuration."""',
        "",
        "import os",
        "from dataclasses import dataclass",
        "from pathlib import Path",
        "",
        "",
        "@dataclass(frozen=True)",
        "class Settings:",
        '    HOST: str = "0.0.0.0"',
        "    PORT: int = 8000",
        '    OLLAMA_URL: str = "http://localhost:11434"',
        '    MODEL_NAME: str = "qwen2.5:1.5b"',
        '    DATABASE_PATH: Path = Path("./motu.db")',
        '    LOG_LEVEL: str = "INFO"',
        "",
        "    @classmethod",
        '    def from_env(cls) -> "Settings":',
        "        return cls(",
        "            HOST=os.getenv('MOTU_HOST', cls.HOST),",
        "            PORT=int(os.getenv('MOTU_PORT', cls.PORT)),",
        "            OLLAMA_URL=os.getenv('MOTU_OLLAMA_URL', cls.OLLAMA_URL),",
        "            MODEL_NAME=os.getenv('MOTU_MODEL_NAME', cls.MODEL_NAME),",
        "            DATABASE_PATH=Path(os.getenv('MOTU_DATABASE_PATH', str(cls.DATABASE_PATH))),",
        "            LOG_LEVEL=os.getenv('MOTU_LOG_LEVEL', cls.LOG_LEVEL),",
        "        )",
        "",
        "",
        "settings = Settings.from_env()",
    ],

    "idgen.py": [
        '"""Time-ordered UUIDv7 generator (RFC 9562)."""',
        "",
        "import time",
        "import uuid",
        "",
        "",
        "def uuid7() -> str:",
        '    timestamp_ms = int(time.time() * 1000)',
        '    timestamp_bytes = timestamp_ms.to_bytes(6, "big")',
        '    rand_bytes = uuid.uuid4().bytes',
        '    v7 = bytearray(16)',
        '    v7[0:6] = timestamp_bytes',
        '    v7[6] = (rand_bytes[6] & 0x0F) | 0x70',
        '    v7[7] = (rand_bytes[7] & 0x3F) | 0x80',
        '    v7[8:16] = rand_bytes[8:16]',
        '    return str(uuid.UUID(bytes=bytes(v7)))',
        "",
        "",
        "def uuid7_to_datetime(uuid_str: str) -> float:",
        '    u = uuid.UUID(uuid_str)',
        '    timestamp_ms = int.from_bytes(u.bytes[0:6], "big")',
        '    return timestamp_ms / 1000.0',
    ],

    "db.py": [
        '"""SQLite database setup with WAL mode."""',
        "",
        "from sqlalchemy import create_engine, event",
        "from sqlalchemy.orm import sessionmaker, declarative_base",
        "",
        "from config import settings",
        "",
        'DB_URL = f"sqlite:///{settings.DATABASE_PATH.resolve()}"',
        "",
        "engine = create_engine(",
        '    DB_URL,',
        '    connect_args={"check_same_thread": False},',
        "    pool_pre_ping=True,",
        "    echo=False,",
        ")",
        "",
        "",
        "@event.listens_for(engine, 'connect')",
        "def _set_sqlite_pragma(dbapi_conn, connection_record):",
        '    cursor = dbapi_conn.cursor()',
        '    cursor.execute("PRAGMA journal_mode=WAL")',
        '    cursor.execute("PRAGMA foreign_keys=ON")',
        '    cursor.execute("PRAGMA synchronous=NORMAL")',
        "    cursor.close()",
        "",
        "",
        "SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)",
        "Base = declarative_base()",
        "",
        "",
        "def init_db() -> None:",
        "    Base.metadata.create_all(bind=engine)",
    ],

    "orm.py": [
        '"""SQLAlchemy ORM models."""',
        "",
        "from datetime import datetime, timezone",
        "from typing import List",
        "",
        "from sqlalchemy import String, Text, Index, ForeignKey",
        "from sqlalchemy.orm import Mapped, mapped_column, relationship",
        "",
        "from db import Base",
        "from idgen import uuid7",
        "",
        "",
        "def utc_now() -> datetime:",
        "    return datetime.now(timezone.utc)",
        "",
        "",
        "class Session(Base):",
        '    __tablename__ = "sessions"',
        "",
        '    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=uuid7)',
        '    title: Mapped[str] = mapped_column(String(255), default="New Chat")',
        '    model: Mapped[str] = mapped_column(String(100), default="qwen2.5:1.5b")',
        "    created_at: Mapped[datetime] = mapped_column(default=utc_now)",
        "    updated_at: Mapped[datetime] = mapped_column(default=utc_now, onupdate=utc_now)",
        "",
        '    messages: Mapped[List["Message"]] = relationship(',
        '        back_populates="session",',
        '        cascade="all, delete-orphan",',
        '        order_by="Message.created_at",',
        "    )",
        "",
        '    __table_args__ = (Index("idx_sessions_updated", "updated_at"),)',
        "",
        "",
        "class Message(Base):",
        '    __tablename__ = "messages"',
        "",
        '    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=uuid7)',
        '    session_id: Mapped[str] = mapped_column(',
        '        String(36), ForeignKey("sessions.id", ondelete="CASCADE"), nullable=False',
        "    )",
        '    role: Mapped[str] = mapped_column(String(20), nullable=False)',
        '    content: Mapped[str] = mapped_column(Text, nullable=False)',
        "    created_at: Mapped[datetime] = mapped_column(default=utc_now)",
        "",
        '    session: Mapped["Session"] = relationship(back_populates="messages")',
        "",
        '    __table_args__ = (Index("idx_messages_session", "session_id", "created_at"),)',
    ],

    "schemas.py": [
        '"""Pydantic request/response models."""',
        "",
        "from datetime import datetime",
        "from typing import List, Optional",
        "",
        "from pydantic import BaseModel, ConfigDict",
        "",
        "",
        "class MessageResponse(BaseModel):",
        "    model_config = ConfigDict(from_attributes=True)",
        "    id: str",
        "    session_id: str",
        "    role: str",
        "    content: str",
        "    created_at: datetime",
        "",
        "",
        "class SessionCreate(BaseModel):",
        "    title: Optional[str] = None",
        "    model: Optional[str] = None",
        "",
        "",
        "class SessionResponse(BaseModel):",
        "    model_config = ConfigDict(from_attributes=True)",
        "    id: str",
        "    title: str",
        "    model: str",
        "    created_at: datetime",
        "    updated_at: datetime",
        "    message_count: int",
        "",
        "",
        "class SessionDetailResponse(BaseModel):",
        "    model_config = ConfigDict(from_attributes=True)",
        "    id: str",
        "    title: str",
        "    model: str",
        "    created_at: datetime",
        "    updated_at: datetime",
        "    messages: List[MessageResponse]",
        "",
        "",
        "class SessionListResponse(BaseModel):",
        "    sessions: List[SessionResponse]",
        "",
        "",
        "class ChatRequest(BaseModel):",
        "    session_id: Optional[str] = None",
        "    message: str",
        "",
        "",
        "class ModelInfo(BaseModel):",
        "    name: str",
        "    size: int",
        "    parameter_count: str",
        "    format: str",
        "",
        "",
        "class ModelListResponse(BaseModel):",
        "    models: List[ModelInfo]",
        "",
        "",
        "class ActiveModelResponse(BaseModel):",
        "    active_model: str",
        "",
        "",
        "class HealthResponse(BaseModel):",
        "    status: str",
        "    version: str",
        "    uptime: float",
        "    cpu_percent: float",
        "    memory_percent: float",
        "    memory_used_gb: float",
        "    ollama_connected: bool",
    ],

    "deps.py": [
        '"""FastAPI database dependency."""',
        "",
        "from typing import Generator",
        "",
        "from sqlalchemy.orm import Session",
        "",
        "from db import SessionLocal",
        "",
        "",
        "def get_db() -> Generator[Session, None, None]:",
        "    db = SessionLocal()",
        "    try:",
        "        yield db",
        "    finally:",
        "        db.close()",
    ],
}

for name, lines in FILES.items():
    path = os.path.join(SRC, name)
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"Created: {path}")

print("\nAll 6 files created. Now run: py test_m1.py")